### ISSUE TITLE
fatal error: stdlib.h: No such file or directory

### ISSUE THREAD

**Issue by yasong** [narke/gcc-cross-compiler#3]
fatal error: stdlib.h: No such file or directory
Need to compile and install glibc?

**Comment by narke** [comment]
Probably, yes.
On a debian-based distro you need libc6-dev package.

**Comment by gthaker** [comment]
I get a similar error. What are the steps needed to build glibc (or any other steps) to overcome this?

>  ~/usr2ppc32/bin/ppc-linux-gnu-gcc -o hello hello.c 
hello.c:1:9: fatal error: stdio.h: No such file or directory
    1 | #include<stdio.h>
      |         ^~~~~~~~~
compilation terminated.


>  ~/usr2ppc32/bin/ppc-linux-gnu-gcc -v
Using built-in specs.
COLLECT_GCC=/export/home/gthaker/usr2ppc32/bin/ppc-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/export/home/gthaker/usr2ppc32/libexec/gcc/ppc-linux-gnu/11.1.0/lto-wrapper
Target: ppc-linux-gnu
Configured with: /proj/home/gthaker/repos/gcc-11.2/ppc32/gcc-11.1.0/configure --target=ppc-linux-gnu --prefix=/export/home/gthaker/usr2ppc32 --program-prefix=ppc-linux-gnu- --with-gnu-as --with-gnu-ld --disable-nls --disable-threads --enable-languages=c --disable-multilib --disable-libgcj --without-headers --disable-shared --enable-lto --disable-werror
Thread model: single
Supported LTO compression algorithms: zlib
gcc version 11.1.0 (GCC)
