### ISSUE TITLE
Build directory for GDB

### ISSUE THREAD

**Issue by kermitdafrog8** [narke/gcc-cross-compiler#4]
GDB needs to build in separate directory from the source. Does not complete the tool chain build.

**Comment by narke** [comment]
I bumped versions of binutils, gcc and gdb and now even gdb compiles.

**Comment by kermitdafrog8** [comment]
> I bumped versions of binutils, gcc and gdb and now even gdb compiles.

Thanks. No more complaints. It seems to finish to the end now.
