### ISSUE TITLE
Is it possible to add PowerPC Macs?

### ISSUE THREAD

**Issue by barracuda156** [narke/gcc-cross-compiler#9]
Is it possible to add support for the following targets?

powerpc-apple-darwin
powerpc64-apple-darwin

**Comment by narke** [comment]
Hi, I originally made it for Linux, so if you want to use it for macOS you should replace "ppc-linux-gnu" by "powerpc-apple-darwin" in this line https://github.com/narke/gcc-cross-compiler/blob/master/toolchain.py#L104 or "ppc64-linux-gnu" by "powerpc64-apple-darwin" on the following line.

**Comment by barracuda156** [comment]
@narke Thank you for responding!
